package com.topnivo.backend.model.constant;

public enum AdminSettings {

    PV_EQUIVALENCE,
    PV_COMMISSION_FACTOR,
    MINIMUM_WITHDRAWAL,
    INDIRECT_COMMISSION_LEVEL_1,
    INDIRECT_COMMISSION_LEVEL_2,
    INDIRECT_COMMISSION_LEVEL_3,
    INDIRECT_COMMISSION_LEVEL_4,
    INDIRECT_COMMISSION_LEVEL_5,
    MATCHING_COMMISSION_LEVEL_1,
    MATCHING_COMMISSION_LEVEL_2,
    MATCHING_COMMISSION_LEVEL_3,
    LEADERSHIP_COMMISSION_FACTOR,
    LEADERSHIP_OVERALL_COMMISSION,
    MONTHLY_NEWLY_REGISTERED_ON_WEAK_LEG_NUMBER,
    MONTHLY_NEWLY_REGISTERED_ON_WEAK_LEG_PRICE,

}
