package com.topnivo.backend.model.constant;

public enum CommissionType {
    BINARY_COMMISSION,
    DIRECT_REFERRAL,
    INDIRECT_REFERRAL,
    MATCHING_COMMISSION,
    UPGRADE_COMMISSION,
    LEADERSHIP_COMMISSION,
    NEWLY_REGISTERED_COUNTER_COMMISSION,
    UNILEVEL_COMMISSION,
    REPUCHASE_COMMISSION,
    RANK_COMMISSION,
    LEADERSHIP_CELEBRATION_COMMISSION,
    PREMIUM_STORE_COMMISSION,
    CHECK_MARCH_COMMISSION,
    SERVICE_CENTER_COMMISSION,
    HIGHEST_RANKING_COMMISSION,

}
